# Generated by Django 5.2 on 2025-04-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='propuestas',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='redes_sociales',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='lista',
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_fundacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='siglas',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('votos', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='scraper.candidato')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultadoElectoral',
        ),
    ]
